# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getresults_patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(max_length=2)),
                ('specimen_condition', models.CharField(blank=True, max_length=2, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocol')),
                ('site_code', models.CharField(blank=True, max_length=2, null=True)),
                ('batch_identifier', models.CharField(editable=False, max_length=25, null=True)),
                ('batch_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='Open', editable=False, max_length=10)),
                ('item_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(max_length=2)),
                ('specimen_condition', models.CharField(blank=True, max_length=2, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocol')),
                ('site_code', models.CharField(blank=True, max_length=2, null=True)),
                ('collection_datetime', models.DateTimeField()),
                ('clinician_initials', models.CharField(blank=True, max_length=3, null=True, verbose_name="Clinician's initials")),
                ('specimen_reference', models.CharField(blank=True, max_length=25, null=True)),
                ('tube_count', models.IntegerField()),
                ('receive_identifier', models.CharField(editable=False, max_length=25, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getresults_receive.Batch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getresults_patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReceive',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(db_index=True, editable=False, help_text='System field. UUID primary key.')),
                ('specimen_type', models.CharField(max_length=2)),
                ('specimen_condition', models.CharField(blank=True, max_length=2, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocol')),
                ('site_code', models.CharField(blank=True, max_length=2, null=True)),
                ('receive_identifier', models.CharField(db_index=True, editable=False, max_length=25)),
                ('receive_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('specimen_reference', models.CharField(blank=True, help_text="A unique reference for this patient's specimen", max_length=25, null=True)),
                ('collection_datetime', models.DateTimeField()),
                ('clinician_initials', models.CharField(max_length=3, verbose_name="Clinician's initials")),
                ('tube_count', models.IntegerField(default=1, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='getresults_patient.Patient')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical receive',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(max_length=2)),
                ('specimen_condition', models.CharField(blank=True, max_length=2, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocol')),
                ('site_code', models.CharField(blank=True, max_length=2, null=True)),
                ('receive_identifier', models.CharField(editable=False, max_length=25, unique=True)),
                ('receive_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('specimen_reference', models.CharField(blank=True, help_text="A unique reference for this patient's specimen", max_length=25, null=True)),
                ('collection_datetime', models.DateTimeField()),
                ('clinician_initials', models.CharField(max_length=3, verbose_name="Clinician's initials")),
                ('tube_count', models.IntegerField(default=1, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getresults_patient.Patient')),
            ],
            options={
                'db_table': 'getresults_receive',
            },
        ),
        migrations.AlterUniqueTogether(
            name='receive',
            unique_together=set([('patient', 'collection_datetime', 'specimen_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together=set([('batch', 'patient', 'collection_datetime', 'specimen_type')]),
        ),
    ]
